# Rule identifier to exclude
disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- for_where
- unused_closure_parameter
- force_cast
- no_fallthrough_only
- multiple_closures_with_trailing_closure

- function_body_length

# Optional rule
opt_in_rules:

# Path to include in Lint
included:

# Path to ignore in Lint
excluded:
- Pods
